movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:movie_id>', views.detail, name='detail'),
]

vidly/urls.py
from django.contrib import admin
from django.urls import include, path
from api.models import MovieResource, GenreResource
from . import views

movie_resource = MovieResource()
genre_resource = GenreResource()

urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('api/', include(movie_resource.urls)),
    path('api/', include(genre_resource.urls)),
]

api/models.py
from django.db import models
from tastypie.resources import ModelResource
from movies.models import Movie, Genre

# Create your models here.
class MovieResource(ModelResource):
    class Meta:
        queryset = Movie.objects.all()
        resource_name = 'movies'
       
class GenreResource(ModelResource):
    class Meta:
        queryset = Genre.objects.all()
        resource_name = 'genres'

movies/models.py
from django.db import models
from django.utils import timezone

class Genre(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return str(self.name)
      
class Movie(models.Model):
    title = models.CharField(max_length=255)
    release_year = models.IntegerField()
    number_in_stock = models.IntegerField()
    daily_rate = models.FloatField()
# genre = models.ForeignKey(Genre, on_delete=models.SET_NULL, null=True)
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)
    date_created = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title + " " + str(self.release_year) + " " + str(self.number_in_stock) + " " + str(self.daily_rate) + " " + str(self.genre) + " " + str(self.date_created)

api/views.py
from django.shortcuts import render

# Create your views here.

movies/views.py
from django.http import Http404, HttpResponse
from django.shortcuts import get_object_or_404, render
from . models import Genre, Movie

# Create your views here.

def index(request):
    movies = Movie.objects.all()
    # output = ', '.join([m.title for m in movies])
    # return HttpResponse(output)
    return render(request, 'movies/index.html', {'movies': movies})

def detail(request, movie_id):
    movie = get_object_or_404(Movie,id=movie_id)
    return render(request, 'movies/detail.html', {'movie': movie})

vidly/views.py
from django.shortcuts import render

def home(request):
    """
    Render the home page.
    
    Args:
        request: The HTTP request object.
    
    Returns:
        HttpResponse: The rendered home page.
    """
    return render(request, 'home.html')

movies/templates/movies/detail.html
{%  extends "base.html"%}

{% block content %}
<dl>
    <dt>Title</dt>
    <dd>{{ movie.title }}</dd>
    <dt>Release Year</dt>
    <dd>{{ movie.release_year }}</dd>
    <dt>Number in Stock</dt>
    <dd>{{ movie.number_in_stock }}</dd>
    <dt>Daily Rate</dt>
    <dd>{{ movie.daily_rate }}</dd>
{% endblock %}

movies/templates/movies/index.html
{% extends "base.html" %}


{% block content %}

<table  class="table table-striped table-hover">
    <thead>
        <tr>
            <th>Title</th>
            <th>Genra</th>
            <th>Stock</th>
            <th>Daily Rate</th>
        </tr>
    </thead>
    <tbody>
        {% for movie in movies %}
        <tr>
            <td><a href="{% url 'movies:detail' movie.id %}">{{movie.title }}</a></td>
            <td>{{ movie.release_year }}</td>
            <td>{{ movie.number_in_stock }}</td>
            <td>{{ movie.daily_rate }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-SgOJa3DmI69IUzQ2PVdRZhwQ+dy64/BUtbMJw1MZ8t5HZApcHrRKUc4W0kG879m7" crossorigin="anonymous" />

    <title>Vidly</title>
  </head>
  <body>
    <header>
      <!-- As a heading -->
      <nav class="navbar bg-body-tertiary">
        <div class="container-fluid">
          <span class="navbar-brand mb-0 h1">Vidly</span>
        </div>
      </nav>
    </header>

    <main class="container mt-4">
      {% block content %}
      {% endblock %}
    </main>

    <footer>
      <p>&copy; 2025 Pablo Ortiz</p>
    </footer>
  </body>
</html>

templates/home.html
{% extends "base.html" %}
{% block content %}
<a href="{% url 'movies:index' %}">Movies</a>
{% endblock %}